version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: ./MercadinhoFront/Dockerfile
    volumes:
      - ./MercadinhoFront/pages:/var/html/www
    ports:
      - 80:80
  spring:
    build:
      context: .
      dockerfile: ./Mercadinho/Dockerfile
    ports:
      - 8080:8080
    links:
      - postgres
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: desafioHappe
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - 8083:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: supersenha
    logging:
      driver: none